//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FirstWebApplication
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MenuDetail
    {
        public int ItemID { get; set; }
        [Display(Name = "Item Name")]
        [Required(ErrorMessage = "Item Name is Required..")]
        [StringLength(45, MinimumLength = 5, ErrorMessage = "Item Name length must between 5 to 45..")]
        public string Name { get; set; }

        public byte[] Image { get; set; }

        [Display(Name = "Meal Type")]
        [Required(ErrorMessage = "Type is Required..")]
        public int TypeID { get; set; }

        [Required(ErrorMessage = "Price is Required..")]
        [Range(1, int.MaxValue, ErrorMessage = "Price must be positive")]
        public int Price { get; set; }
        public bool Veg { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual MealType MealType { get; set; }
    }
}
