//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace FirstWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRegistration
    {
        public int StudentID { get; set; }

        [Display(Name = "UserName")]
        [Required(ErrorMessage = "UserName is Required..")]
        [StringLength(20,MinimumLength =5,ErrorMessage ="UserName length must between 5 to 20..")]
        public string StudentName { get; set; }

        [Required(ErrorMessage = "Password is Required..")]
        public string Password { get; set; }

        [Required(ErrorMessage = "EmailID is Required..")]
        [EmailAddress(ErrorMessage = "Please Enter Valid Email..")]
        public string Email { get; set; }

        [Display(Name = "PhoneNumber")]
        public long Mobile { get; set; }
    }
}
